name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        # Run tests if they exist, otherwise skip
        if [ -d "../automation" ]; then
          python -m pytest ../automation/ -v || echo "Tests failed, continuing deployment"
        else
          echo "No tests directory found, skipping tests"
        fi
        
    - name: Build documentation
      run: |
        # Copy frontend files to docs for GitHub Pages
        cp -r frontend/* docs/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
